# 照明：sea_lantern を格子状に配置（21x21の床をカバー）
setblock ~-10 ~1 ~-10 minecraft:sea_lantern
setblock ~-10 ~1 ~-6 minecraft:sea_lantern
setblock ~-10 ~1 ~-2 minecraft:sea_lantern
setblock ~-10 ~1 ~2 minecraft:sea_lantern
setblock ~-10 ~1 ~6 minecraft:sea_lantern
setblock ~-10 ~1 ~10 minecraft:sea_lantern
setblock ~-6 ~1 ~-10 minecraft:sea_lantern
setblock ~-6 ~1 ~-6 minecraft:sea_lantern
setblock ~-6 ~1 ~-2 minecraft:sea_lantern
setblock ~-6 ~1 ~2 minecraft:sea_lantern
setblock ~-6 ~1 ~6 minecraft:sea_lantern
setblock ~-6 ~1 ~10 minecraft:sea_lantern
setblock ~-2 ~1 ~-10 minecraft:sea_lantern
setblock ~-2 ~1 ~-6 minecraft:sea_lantern
setblock ~-2 ~1 ~-2 minecraft:sea_lantern
setblock ~-2 ~1 ~2 minecraft:sea_lantern
setblock ~-2 ~1 ~6 minecraft:sea_lantern
setblock ~-2 ~1 ~10 minecraft:sea_lantern
setblock ~2 ~1 ~-10 minecraft:sea_lantern
setblock ~2 ~1 ~-6 minecraft:sea_lantern
setblock ~2 ~1 ~-2 minecraft:sea_lantern
setblock ~2 ~1 ~2 minecraft:sea_lantern
setblock ~2 ~1 ~6 minecraft:sea_lantern
setblock ~2 ~1 ~10 minecraft:sea_lantern
setblock ~6 ~1 ~-10 minecraft:sea_lantern
setblock ~6 ~1 ~-6 minecraft:sea_lantern
setblock ~6 ~1 ~-2 minecraft:sea_lantern
setblock ~6 ~1 ~2 minecraft:sea_lantern
setblock ~6 ~1 ~6 minecraft:sea_lantern
setblock ~6 ~1 ~10 minecraft:sea_lantern
setblock ~10 ~1 ~-10 minecraft:sea_lantern
setblock ~10 ~1 ~-6 minecraft:sea_lantern
setblock ~10 ~1 ~-2 minecraft:sea_lantern
setblock ~10 ~1 ~2 minecraft:sea_lantern
setblock ~10 ~1 ~6 minecraft:sea_lantern
setblock ~10 ~1 ~10 minecraft:sea_lantern
