execute as @a positioned ~8 ~-8 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-7 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-6 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-5 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-4 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-3 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~-2 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~ ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~0 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~1 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~2 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~3 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~4 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~5 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~6 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~7 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~8 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~9 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~8 ~10 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~0 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-9 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-8 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-7 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-6 ~10 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~-9 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~-8 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~-7 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~-6 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~-5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~-4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~-3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~-2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~ if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~0 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~1 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~2 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~3 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~4 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~
execute as @a positioned ~9 ~-5 ~5 if block ~ ~ ~ mangrove_leaves run particle fused:mangrove_leaf ~ ~ ~