scoreboard objectives add time dummy
scoreboard players add @a time 1

execute as @a[scores={time=1}] at @s run function acacia9
execute as @a[scores={time=40}] at @s run function acacia5.2
execute as @a[scores={time=80}] at @s run function acacia7.2
execute as @a[scores={time=92}] at @s run function acacia9.2
execute as @a[scores={time=110}] at @s run function acacia4
execute as @a[scores={time=142}] at @s run function acacia1
execute as @a[scores={time=180}] at @s run function acacia5
execute as @a[scores={time=530}] at @s run function acacia2.2
execute as @a[scores={time=560}] at @s run function acacia8
execute as @a[scores={time=200}] at @s run function acacia2
execute as @a[scores={time=220}] at @s run function acacia4.2
execute as @a[scores={time=242}] at @s run function acacia8.2
execute as @a[scores={time=590}] at @s run function acacia6.2
execute as @a[scores={time=342}] at @s run function acacia6
execute as @a[scores={time=370}] at @s run function acacia1.2
execute as @a[scores={time=402}] at @s run function acacia3
execute as @a[scores={time=452}] at @s run function acacia3.2
execute as @a[scores={time=492}] at @s run function acacia7

execute as @a[scores={time=1}] at @s run function azalea9
execute as @a[scores={time=40}] at @s run function azalea5.2
execute as @a[scores={time=80}] at @s run function azalea7.2
execute as @a[scores={time=92}] at @s run function azalea9.2
execute as @a[scores={time=110}] at @s run function azalea4
execute as @a[scores={time=142}] at @s run function azalea1
execute as @a[scores={time=180}] at @s run function azalea5
execute as @a[scores={time=530}] at @s run function azalea2.2
execute as @a[scores={time=560}] at @s run function azalea8
execute as @a[scores={time=200}] at @s run function azalea2
execute as @a[scores={time=220}] at @s run function azalea4.2
execute as @a[scores={time=242}] at @s run function azalea8.2
execute as @a[scores={time=590}] at @s run function azalea6.2
execute as @a[scores={time=342}] at @s run function azalea6
execute as @a[scores={time=370}] at @s run function azalea1.2
execute as @a[scores={time=402}] at @s run function azalea3
execute as @a[scores={time=452}] at @s run function azalea3.2
execute as @a[scores={time=492}] at @s run function azalea7

execute as @a[scores={time=1}] at @s run function azaleaflowered9
execute as @a[scores={time=40}] at @s run function azaleaflowered5.2
execute as @a[scores={time=80}] at @s run function azaleaflowered7.2
execute as @a[scores={time=92}] at @s run function azaleaflowered9.2
execute as @a[scores={time=110}] at @s run function azaleaflowered4
execute as @a[scores={time=142}] at @s run function azaleaflowered1
execute as @a[scores={time=180}] at @s run function azaleaflowered5
execute as @a[scores={time=530}] at @s run function azaleaflowered2.2
execute as @a[scores={time=560}] at @s run function azaleaflowered8
execute as @a[scores={time=200}] at @s run function azaleaflowered2
execute as @a[scores={time=220}] at @s run function azaleaflowered4.2
execute as @a[scores={time=242}] at @s run function azaleaflowered8.2
execute as @a[scores={time=590}] at @s run function azaleaflowered6.2
execute as @a[scores={time=342}] at @s run function azaleaflowered6
execute as @a[scores={time=370}] at @s run function azaleaflowered1.2
execute as @a[scores={time=402}] at @s run function azaleaflowered3
execute as @a[scores={time=452}] at @s run function azaleaflowered3.2
execute as @a[scores={time=492}] at @s run function azaleaflowered7

execute as @a[scores={time=1}] at @s run function birch9
execute as @a[scores={time=40}] at @s run function birch5.2
execute as @a[scores={time=80}] at @s run function birch7.2
execute as @a[scores={time=92}] at @s run function birch9.2
execute as @a[scores={time=110}] at @s run function birch4
execute as @a[scores={time=142}] at @s run function birch1
execute as @a[scores={time=180}] at @s run function birch5
execute as @a[scores={time=530}] at @s run function birch2.2
execute as @a[scores={time=560}] at @s run function birch8
execute as @a[scores={time=200}] at @s run function birch2
execute as @a[scores={time=220}] at @s run function birch4.2
execute as @a[scores={time=242}] at @s run function birch8.2
execute as @a[scores={time=590}] at @s run function birch6.2
execute as @a[scores={time=342}] at @s run function birch6
execute as @a[scores={time=370}] at @s run function birch1.2
execute as @a[scores={time=402}] at @s run function birch3
execute as @a[scores={time=452}] at @s run function birch3.2
execute as @a[scores={time=492}] at @s run function birch7

execute as @a[scores={time=1}] at @s run function oak9
execute as @a[scores={time=40}] at @s run function oak5.2
execute as @a[scores={time=80}] at @s run function oak7.2
execute as @a[scores={time=92}] at @s run function oak9.2
execute as @a[scores={time=110}] at @s run function oak4
execute as @a[scores={time=142}] at @s run function oak1
execute as @a[scores={time=180}] at @s run function oak5
execute as @a[scores={time=530}] at @s run function oak2.2
execute as @a[scores={time=560}] at @s run function oak8
execute as @a[scores={time=200}] at @s run function oak2
execute as @a[scores={time=220}] at @s run function oak4.2
execute as @a[scores={time=242}] at @s run function oak8.2
execute as @a[scores={time=590}] at @s run function oak6.2
execute as @a[scores={time=342}] at @s run function oak6
execute as @a[scores={time=370}] at @s run function oak1.2
execute as @a[scores={time=402}] at @s run function oak3
execute as @a[scores={time=452}] at @s run function oak3.2
execute as @a[scores={time=492}] at @s run function oak7

execute as @a[scores={time=1}] at @s run function spruce9
execute as @a[scores={time=40}] at @s run function spruce5.2
execute as @a[scores={time=80}] at @s run function spruce7.2
execute as @a[scores={time=92}] at @s run function spruce9.2
execute as @a[scores={time=110}] at @s run function spruce4
execute as @a[scores={time=142}] at @s run function spruce1
execute as @a[scores={time=180}] at @s run function spruce5
execute as @a[scores={time=530}] at @s run function spruce2.2
execute as @a[scores={time=560}] at @s run function spruce8
execute as @a[scores={time=200}] at @s run function spruce2
execute as @a[scores={time=220}] at @s run function spruce4.2
execute as @a[scores={time=242}] at @s run function spruce8.2
execute as @a[scores={time=590}] at @s run function spruce6.2
execute as @a[scores={time=342}] at @s run function spruce6
execute as @a[scores={time=370}] at @s run function spruce1.2
execute as @a[scores={time=402}] at @s run function spruce3
execute as @a[scores={time=452}] at @s run function spruce3.2
execute as @a[scores={time=492}] at @s run function spruce7

execute as @a[scores={time=1}] at @s run function dark_oak9
execute as @a[scores={time=40}] at @s run function dark_oak5.2
execute as @a[scores={time=80}] at @s run function dark_oak7.2
execute as @a[scores={time=92}] at @s run function dark_oak9.2
execute as @a[scores={time=110}] at @s run function dark_oak4
execute as @a[scores={time=142}] at @s run function dark_oak1
execute as @a[scores={time=180}] at @s run function dark_oak5
execute as @a[scores={time=530}] at @s run function dark_oak2.2
execute as @a[scores={time=560}] at @s run function dark_oak8
execute as @a[scores={time=200}] at @s run function dark_oak2
execute as @a[scores={time=220}] at @s run function dark_oak4.2
execute as @a[scores={time=242}] at @s run function dark_oak8.2
execute as @a[scores={time=590}] at @s run function dark_oak6.2
execute as @a[scores={time=342}] at @s run function dark_oak6
execute as @a[scores={time=370}] at @s run function dark_oak1.2
execute as @a[scores={time=402}] at @s run function dark_oak3
execute as @a[scores={time=452}] at @s run function dark_oak3.2
execute as @a[scores={time=492}] at @s run function dark_oak7

execute as @a[scores={time=1}] at @s run function jungle9
execute as @a[scores={time=40}] at @s run function jungle5.2
execute as @a[scores={time=80}] at @s run function jungle7.2
execute as @a[scores={time=92}] at @s run function jungle9.2
execute as @a[scores={time=110}] at @s run function jungle4
execute as @a[scores={time=142}] at @s run function jungle1
execute as @a[scores={time=180}] at @s run function jungle5
execute as @a[scores={time=530}] at @s run function jungle2.2
execute as @a[scores={time=560}] at @s run function jungle8
execute as @a[scores={time=200}] at @s run function jungle2
execute as @a[scores={time=220}] at @s run function jungle4.2
execute as @a[scores={time=242}] at @s run function jungle8.2
execute as @a[scores={time=590}] at @s run function jungle6.2
execute as @a[scores={time=342}] at @s run function jungle6
execute as @a[scores={time=370}] at @s run function jungle1.2
execute as @a[scores={time=402}] at @s run function jungle3
execute as @a[scores={time=452}] at @s run function jungle3.2
execute as @a[scores={time=492}] at @s run function jungle7

execute as @a[scores={time=1}] at @s run function mangrove9
execute as @a[scores={time=40}] at @s run function mangrove5.2
execute as @a[scores={time=80}] at @s run function mangrove7.2
execute as @a[scores={time=92}] at @s run function mangrove9.2
execute as @a[scores={time=110}] at @s run function mangrove4
execute as @a[scores={time=142}] at @s run function mangrove1
execute as @a[scores={time=180}] at @s run function mangrove5
execute as @a[scores={time=530}] at @s run function mangrove2.2
execute as @a[scores={time=560}] at @s run function mangrove8
execute as @a[scores={time=200}] at @s run function mangrove2
execute as @a[scores={time=220}] at @s run function mangrove4.2
execute as @a[scores={time=242}] at @s run function mangrove8.2
execute as @a[scores={time=590}] at @s run function mangrove6.2
execute as @a[scores={time=342}] at @s run function mangrove6
execute as @a[scores={time=370}] at @s run function mangrove1.2
execute as @a[scores={time=402}] at @s run function mangrove3
execute as @a[scores={time=452}] at @s run function mangrove3.2
execute as @a[scores={time=492}] at @s run function mangrove7

execute as @a[scores={time=596..4000}] at @s run scoreboard players set @s time 0